service: git-lambda-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  role: arn:aws:iam::667505010803:role/service-role/lambda-role-8vrgj12i
  vpc:
    securityGroupIds:
      - sg-0666adccfd087e375
    subnetIds:
      - subnet-0f31c5f562806ea28
      - subnet-0ae98dfbeb28f2248
  deploymentBucket:
    name: serverless-deployment-main-bucket
  deploymentPrefix: git-lambda-test-DEV

functions:
  app:
    handler: index.hello
     events:
      - http: ANY /
      - http: 'ANY {proxy+}'